version: 0.2
env:
  variables:
    IMAGE_TAG: latest
phases:
  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=${AWS_DEFAULT_REGION}
      - REPO_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_REPO_NAME}
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${REPO_URI}
  build:
    commands:
      - docker build -t ${REPO_URI}:${IMAGE_TAG} .
  post_build:
    commands:
      - docker push ${REPO_URI}:${IMAGE_TAG}
artifacts:
  files:
    - "**/*"
